version: '3'
services:
  db: 
    image: mysql:5.7
    ports: 
      - "3336:3306"
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: '1234'
    volumes: 
    - ./mysql-data/:/var/lib/mysql
